### ISSUE TITLE
Required Tag Association

### ISSUE THREAD

**Issue by rmacklin** [AppFolioOnboarding/image-sharer-wilsonyqm#12]
#### As a user I want all images to have at least one tag.

Acceptance criteria:
- [ ] I cannot save an image without adding at least one tag.
- [ ] An error message is associated with the appropriate input field when a
  tag is not provided.

Dependencies:
- Image Tags

**Comment by wilsonyqm** [comment]
I can add one line of code ```  validates :tag_list, presence: true``` to make this story work, maybe one more test. Is that right? @bboe

**Comment by bboe** [comment]
Try it and see what happens :)
