### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by rmacklin** [AppFolioOnboarding/image-sharer-wilsonyqm#14]
#### As an application hoster I want to restrict some functionality to specific users.

- [x] Logged out users are restricted to read-only access.
- [x] Links to non-read actions are not shown to logged out users.
- [x] Attempting to access a page that requires authentication redirects you to
  the login page.
- [x] Upon successful login, you are redirected back to where you had tried to
  navigate.
- [x] Every image is associated with the user that added it.
- [x] Only the user that added an image can delete that image.

Discussion topics:
- [ ] If we wanted to add a lot of authorization rules, how might we want to
  organize our code to keep it maintainable?

Further reading:
- https://github.com/elabs/pundit

Dependencies:
- Authentication

**Comment by wilsonyqm** [comment]
I think user cannot share other user's image, not only just for the delete action. It would be more fun to implement the hidden share button with authentication.

**Comment by rmacklin** [comment]
I don't understand what you are saying. Logged out users should not be able to share, edit, add, or delete images. _Logged in_ users of our application should be able to share any image. But only the user who uploaded an image should be able to delete that image (to prevent a malicious user deleting everyone else's images).

**Comment by wilsonyqm** [comment]
I thought the user could not share or edit the image uploaded by other user.

**Comment by rmacklin** [comment]
Are you saying that something in the issue description was confusing and it made you think that? To me, it seems clear that only `delete` needs an extra permission:
> Only the user that added an image can delete that image.

but if that's not clear, let me know how you think we can improve the issue description.
