### ISSUE TITLE
Image URL Validation

### ISSUE THREAD

**Issue by rmacklin** [AppFolioOnboarding/image-sharer-wilsonyqm#4]
#### As a user I want to be prevented from submitting invalid image URLs.

Acceptance criteria:
- [x] I cannot successfully save an image with an invalid URL.
- [x] An error message is associated with the appropriate input field on
  failure.

Discussion Topic:
- [x] What is a valid image URL?

Dependencies:
- Save Image Link

**Comment by bboe** [comment]
@wilsonyqm I see that the "pull request" label is set, however, I don't see a pull request associated with the issue. Could you please update either the label on the issue to reflect the status (let me know if you're unsure what it should be), or add the pull request and make the necessary links?
